export const LOCATORS = {
    SEARCH_FIELD: '.fast-search__input',
    SWITCH_FRAME: `[class="modal-iframe"]`,
    SEARCH_CLOSE: `.search__close`,
    SAMSUNG: `text = SM-A525F/DS 4GB/128GB`,
    ADD_BUCKET: `(//a[@class="button-style button-style_base-alter button-style_primary product-aside__button product-aside__button_narrow product-aside__button_cart button-style_expletive"])[1]`,
    ELECTRONIC: `[class="catalog-navigation-classifier__item-icon catalog-navigation-classifier__item-icon_id_1"]`,
    FIND_TV: `//*[contains(text(),"Телевидение")]`,
    ADD_TV: `[href="https://catalog.onliner.by/tv"]`,
    CHECK_BOX_TV: `//*[@value="lg"]`,
    WEATHER: `[href="https://pogoda.onliner.by/"]`,
    CITY_FIRST: `[class="js-weather-city"]`,
    CITY_SECOND: `//*[contains(text(),"Бобруйск")]`,
    AUTOR: `[class="auth-bar__item auth-bar__item--text"]`,
    LOGIN: `[placeholder="Ник или e-mail"]`,
    PASSWORD: `[placeholder="Пароль"]`,
    AUTH_FORM: `[class*="middle auth-form"]`,
    OIL_FRIST: `text = Моторные масла`,
    OIL_SECOND: `text = Моторное масло Eurorepar Premium C2 5W-30 5л`,
    CURRENCY: `[class="_u js-currency-amount"]`,
    RESULT: `[class="title to-be-removed"]`,
    CLEVER: `[class="b-top-navigation-clover"]`,
    ADD_CART: `text = КЛЕВЕР`,
};
