export const locators = {
    searchField: '.fast-search__input',
    switchFrame: `[class="modal-iframe"]`,
    searchClose: `.search__close`,
    samsung: `text = SM-A525F/DS 4GB/128GB`,
    addBucket1: `(//a[@class="button-style button-style_base-alter button-style_primary product-aside__button product-aside__button_narrow product-aside__button_cart button-style_expletive"])[1]`,
    electronic: `[class="catalog-navigation-classifier__item-icon catalog-navigation-classifier__item-icon_id_1"]`,
    findTv: `//*[contains(text(),"Телевидение")]`,
    addTv: `[href="https://catalog.onliner.by/tv"]`,
    checkBoxTv: `//*[@value="lg"]`,
    weather1: `[href="https://pogoda.onliner.by/"]`,
    city: `[class="js-weather-city"]`,
    city1: `//*[contains(text(),"Бобруйск")]`,
    autor: `[class="auth-bar__item auth-bar__item--text"]`,
    login: `[placeholder="Ник или e-mail"]`,
    password: `[placeholder="Пароль"]`,
    authForm: `[class*="middle auth-form"]`,
    oil: `text = Моторные масла`,
    oil2: `text = Моторное масло Eurorepar Premium C2 5W-30 5л`,
    currency: `[class="_u js-currency-amount"]`,
    result: `[class="title to-be-removed"]`,
    clever: `[class="b-top-navigation-clover"]`,
    addCart: `text = КЛЕВЕР`,
};
